<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV5nDUdq\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV5nDUdq/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerV5nDUdq.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerV5nDUdq\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerV5nDUdq\appAppKernelProdContainer([
    'container.build_hash' => 'V5nDUdq',
    'container.build_id' => 'd64488cc',
    'container.build_time' => 1764938970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV5nDUdq');
