<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'StripeOfficial\Controllers\admin\SkipCloudSyncDependenciesController' shared service.

return $this->services['StripeOfficial\\Controllers\\admin\\SkipCloudSyncDependenciesController'] = new \StripeOfficial\Controllers\admin\SkipCloudSyncDependenciesController($this);
